# Generated by Django 3.2.9 on 2021-12-06 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_auto_20211206_0857'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='ingredientsss',
            new_name='ingredients',
        ),
    ]
