# Generated by Django 3.2.9 on 2021-11-16 11:28

from django.db import migrations, models
import django.db.models.deletion
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=128, verbose_name='Ingredients title')),
                ('amount', models.IntegerField(verbose_name='Ingredients amount')),
                ('units', models.CharField(choices=[('KG', 'KG'), ('GR', 'GR')], default='GR', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True, verbose_name='Tag title')),
                ('slug', models.SlugField(unique=True, verbose_name='Tag slug')),
                ('color', models.CharField(max_length=7, verbose_name='HEX formated color for tag')),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=128, verbose_name='Recipe title')),
                ('text', models.TextField(verbose_name='Recipe text')),
                ('image', sorl.thumbnail.fields.ImageField(blank=True, null=True, upload_to='recipes/', verbose_name='Image')),
                ('time', models.TimeField(verbose_name='Time to cook')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to='users.user', verbose_name='Recipes author')),
                ('ingredients', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.ingredients', verbose_name='Ingredients for recipe')),
                ('tags', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='recipes.tag', verbose_name='Tags')),
            ],
        ),
    ]
