# Generated by Django 3.2.9 on 2021-11-29 11:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=128, verbose_name='Ingredients title')),
                ('measurement_unit', models.CharField(max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Tag title')),
                ('slug', models.SlugField(unique=True, verbose_name='Tag slug')),
                ('color', models.CharField(max_length=7, verbose_name='HEX formated color for tag')),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_favorited', models.BooleanField(default=True)),
                ('is_in_shopping_cart', models.BooleanField(default=False)),
                ('name', models.TextField(max_length=128, verbose_name='Recipe title')),
                ('image', sorl.thumbnail.fields.ImageField(blank=True, null=True, upload_to='recipes/', verbose_name='Image')),
                ('text', models.TextField(verbose_name='Recipe text')),
                ('cooking_time', models.IntegerField(verbose_name='Time to cook')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recipe', to=settings.AUTH_USER_MODEL, verbose_name='author')),
                ('ingredients', models.ManyToManyField(to='recipes.Ingredients', verbose_name='Ingredients for recipe')),
                ('tags', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.tag', verbose_name='Tags')),
            ],
        ),
    ]
