# Generated by Django 3.2.9 on 2021-11-18 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredients',
            old_name='units',
            new_name='measurement_unit',
        ),
        migrations.RenameField(
            model_name='ingredients',
            old_name='title',
            new_name='name',
        ),
    ]
