# Generated by Django 3.2.9 on 2021-11-18 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_is_subscribed'),
        ('recipes', '0005_auto_20211118_1112'),
    ]

    operations = [
        migrations.CreateModel(
            name='IsSubscribed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscribing', to='users.user')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriber', to='users.user')),
            ],
        ),
        migrations.AddConstraint(
            model_name='issubscribed',
            constraint=models.UniqueConstraint(fields=('user', 'author'), name='unique_subs'),
        ),
    ]
