# Generated by Django 3.2.9 on 2021-11-18 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_auto_20211118_1145'),
    ]

    operations = [
        migrations.DeleteModel(
            name='IsSubscribed',
        ),
    ]
