# Generated by Django 3.2.9 on 2021-11-18 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0010_auto_20211118_1802'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='is_in_shoping_cart',
            new_name='is_in_shopping_cart',
        ),
    ]
